[package]
name = "tau_factory"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/tau_factory.rs"

[[bin]]
name = "tau-factory"
path = "src/main.rs"

[dependencies]
chrono.workspace = true
ciborium.workspace = true
nanoid.workspace = true
redb.workspace = true
serde.workspace = true
smol.workspace = true
tau-actions = { path = "../../../tau/crates/tau-actions" }
tau-extension = { path = "../../../tau/crates/tau-extension" }
tau-proto = { path = "../../../tau/crates/tau-proto" }
tau_task = { path = "../tau_task" }

[dev-dependencies]
tempfile.workspace = true
