[package]
name = "tau_task"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/tau_task.rs"

[dependencies]
chrono.workspace = true
serde.workspace = true
tau-proto = { path = "../../../tau/crates/tau-proto" }
thiserror.workspace = true
